### PR TITLE
[Feature request] Java support for VSCode

### PR DESCRIPTION
**Pull request by paulvi**
this is actually feature request for  Java support in VSCode.

### CODE REVIEW

**Comment by rafaelyates** [comment]
Are you guys planning to add Java support? This would be really nice.

**Comment by janos-ss** [comment]
I created a ticket for this in our issue tracker: https://jira.sonarsource.com/browse/SLVSCODE-35

**Comment by paulvi** [comment]
Thanks

**Comment by rufreakde** [comment]
Still now Update here?

**Comment by toniperezfer** [comment]
when the feature request will be available?

**Pull request closed without merging**
