### PR TITLE
Add Typescript support and rules section

### PR DESCRIPTION
**Pull request by juboucher**

### CODE REVIEW

**Comment by DanielRuf** [comment]
How can we enable rules?

**Comment by henryju** [comment]
For VSCode there is currently no way to configure rules without using connected mode with a SonarQube server. This is something we should improve this year.
https://jira.sonarsource.com/browse/MMF-1277

**Comment by DanielRuf** [comment]
Would be great to have this feature in the future.

**Comment by DanielRuf** [comment]
Because the rule for console.log is not used in SonarLint for VSCode as it seems (I use SonarScanner 3.3.0).

**Pull request merged**
