### PR TITLE
Update README with new Clean Code wording and link from Marketing

### PR DESCRIPTION
**Pull request by david-cho-lerat-sonarsource**

### CODE REVIEW

**Comment by jblievremont** [comment]
Hey @david-cho-lerat-sonarsource thanks for this PR.

Could you please make sure to check with @andrew-osborne-sonarsource that these changes are aligned with the product marketing wording that we want to show on the marketplace?

Thanks.

**Comment by david-cho-lerat-sonarsource** [comment]
Hi Jean-Baptiste, the wording comes from Jonathan Grabowski, cc'd to
this email.

Thanks.


David Cho-Lerat | Sonar

SonarQube Developer

https://sonarsource.com

**Comment by jblievremont** [comment]
After a few discussions with the involved people, I will add a bit of context of why this change was requested, for future reference:

* SEO would like the link to the Clean Code principles visible on high-traffic Web resources
* This repository is one of the top-watched from our organization, so any link on the README will have a huge visibility

As a side effect, the link will also appear on the [Visual Studio marketplace page for SonarLint](https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarlint-vscode) after the next release.

**Review by jblievremont — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
