### PR TITLE
SLVSCODE-25 Allocate port by passing 0 to listen; drop portfinder

### PR DESCRIPTION
**Pull request by saberduck**

### CODE REVIEW

**Comment by saberduck** [comment]
Note that this is based on `sonarts-integration` branch, not on master.

**Comment by henryju** [comment]
@saberduck I have merged branch sonarts-integration into master. Could you rebase this P/R on master?

**Comment by henryju** [comment]
Also could you please create a JIRA ticket for the issue.

**Comment by henryju** [comment]
My bad, ticket is created, just need to mention it in the comment

**Pull request merged**
